name: 'GitHub organization repo topic crawler'
author: 'Ari LiVigni'
description: 'crawl repository topic to collect data'
inputs:
  admin_token:
    description: 'Token with access to repository and topics'
    required: true
  org:
    description: 'The GitHub organization containing the repo'
    required: true
    default: ${{ github.repository_owner }}
  repo_topic:
    description: 'Repo topic to filter on'
    required: true
    default: innersource-ml
  repo_file:
    description: 'Path and file '
    required: true
    default: '.github/models.yml'
runs:
  using: node16
  main: dist/index.js
